export const ALL_INC = [
  {code:'inc_1',grp:'IBM AIX Stack',short:'INC-001',txt:'INC-001: AIX Legacy JFS Log Corruption on Power7 Systems',layers:['os','storage']},
  {code:'inc_2',grp:'IBM AIX Stack',short:'INC-002',txt:'INC-002: AIX ODM Device Catalog Corruption',layers:['os']},
  {code:'inc_3',grp:'IBM AIX Stack',short:'INC-003',txt:'INC-003: AIX NIM Master Subsystem Communications Failure',layers:['os','network']},
  {code:'inc_4',grp:'IBM AIX Stack',short:'INC-004',txt:'INC-004: AIX LPAR AIO Asynchronous I/O Slot Exhaustion',layers:['os','app']},
  {code:'inc_5',grp:'IBM AIX Stack',short:'INC-005',txt:'INC-005: AIX dsh Clustering Command Block Under Dense Tasks',layers:['os','network']},
  {code:'inc_6',grp:'IBM AIX Stack',short:'INC-006',txt:'INC-006: IBM Power9 Asymmetric Memory Thread Contention Core Freeze',layers:['hardware','os']},
  {code:'inc_7',grp:'IBM AIX Stack',short:'INC-007',txt:'INC-007: IBM Power10 PCIe Gen5 Dynamic Reconfiguration LPAR Panic',layers:['hardware','os']},
  {code:'inc_8',grp:'IBM AIX Stack',short:'INC-008',txt:'INC-008: AIX WPAR Shared Kernel Flag Namespace Collision',layers:['os','app']},
  {code:'inc_59',grp:'IBM AIX Stack',short:'INC-059',txt:'INC-059 [CVE-2023-40371]: AIX bellmail Local Privilege Escalation Root Hijack',layers:['os','security']},
  {code:'inc_60',grp:'IBM AIX Stack',short:'INC-060',txt:'INC-060 [CVE-2024-35920]: AIX libperfstat Memory Leak Leading to Kernel Panic',layers:['os']},
  {code:'inc_61',grp:'IBM AIX Stack',short:'INC-061',txt:'INC-061: AIX LVM Quorum Loss Dual Disk Drop',layers:['os','storage']},
  {code:'inc_62',grp:'IBM AIX Stack',short:'INC-062',txt:'INC-062: AIX iSCSI MPIO Path Flapping Dynamic Tracking Freeze',layers:['os','storage','network']},
  {code:'inc_9',grp:'Windows Server Stack',short:'INC-013',txt:'INC-013: Windows Server 2012 R2 Schannel TLS 1.0/1.1 Cipher Drop',layers:['os','web','security']},
  {code:'inc_10',grp:'Windows Server Stack',short:'INC-014',txt:'INC-014: Windows Server 2016 Active Directory Jet Database Corruption',layers:['os','db']},
  {code:'inc_11',grp:'Windows Server Stack',short:'INC-015',txt:'INC-015: Windows Server 2019 COM+ Distributed Transaction Timeout',layers:['os','app']},
  {code:'inc_12',grp:'Windows Server Stack',short:'INC-016',txt:'INC-016: Windows Server 2022 WinNAT Port Exhaustion Microservices',layers:['os','network','app']},
  {code:'inc_13',grp:'Windows Server Stack',short:'INC-017',txt:'INC-017: Windows Server 2025 Hotpatch Signature Rejection',layers:['os','security']},
  {code:'inc_14',grp:'Windows Server Stack',short:'INC-018',txt:'INC-018: Legacy IIS 8.5 Worker Process Deadlock on Obsolete .NET Pools',layers:['web','app']},
  {code:'inc_15',grp:'Windows Server Stack',short:'INC-019',txt:'INC-019: Windows VSS Storage Limit Deadlock',layers:['os','storage','backup']},
  {code:'inc_16',grp:'Windows Server Stack',short:'INC-020',txt:'INC-020: Hyper-V Core CSV Split-Brain Cluster Lock',layers:['os','storage']},
  {code:'inc_63',grp:'Windows Server Stack',short:'INC-021',txt:'INC-021 [CVE-2024-30078]: Windows Network Stack RCE',layers:['os','network','security']},
  {code:'inc_64',grp:'Windows Server Stack',short:'INC-022',txt:'INC-022 [CVE-2025-21290]: Windows Kerberos Security Feature Bypass',layers:['os','security']},
  {code:'inc_65',grp:'Windows Server Stack',short:'INC-023',txt:'INC-023: IIS 10 HTTP/2 Window Size Heap Memory Exhaustion',layers:['web','app']},
  {code:'inc_66',grp:'Windows Server Stack',short:'INC-024',txt:'INC-024: Active Directory LSASS CPU Spike via Crafted LDAP Loop',layers:['os','security','db']},
  {code:'inc_17',grp:'Enterprise Linux Stack',short:'INC-025',txt:'INC-025: RHEL 6 Legacy glibc Mutex Vulnerability Injection',layers:['os']},
  {code:'inc_18',grp:'Enterprise Linux Stack',short:'INC-026',txt:'INC-026: RHEL 7 systemd Unit Controller Memory Leak',layers:['os']},
  {code:'inc_19',grp:'Enterprise Linux Stack',short:'INC-027',txt:'INC-027: RHEL 8 NetworkManager D-Bus Communication Thread Block',layers:['os','network']},
  {code:'inc_20',grp:'Enterprise Linux Stack',short:'INC-028',txt:'INC-028: RHEL 9 XFS Filesystem Quota Allocation Crash',layers:['os','storage']},
  {code:'inc_21',grp:'Enterprise Linux Stack',short:'INC-029',txt:'INC-029: RHEL 10 Podman Engine cgroups v2 Isolation Failure',layers:['os','app']},
  {code:'inc_22',grp:'Enterprise Linux Stack',short:'INC-030',txt:'INC-030: Java 21 Virtual Thread Pinning Deadlock on Linux Nodes',layers:['app']},
  {code:'inc_23',grp:'Enterprise Linux Stack',short:'INC-031',txt:'INC-031: Tomcat 11 Jakarta EE ClassNotFound Loading Drop',layers:['app','web']},
  {code:'inc_24',grp:'Enterprise Linux Stack',short:'INC-032',txt:'INC-032: OpenSSL 3.x Incompatible Legacy Cipher Handshake Refusal',layers:['os','security','web']},
  {code:'inc_24_1',grp:'Enterprise Linux Stack',short:'INC-033',txt:'INC-033 [CVE-2024-6387]: OpenSSH regreSSHion RCE Exploitation',layers:['os','security','network']},
  {code:'inc_24_2',grp:'Enterprise Linux Stack',short:'INC-034',txt:'INC-034 [CVE-2025-0111]: Linux Kernel eBPF Out-of-Bounds Read',layers:['os']},
  {code:'inc_67',grp:'Enterprise Linux Stack',short:'INC-035',txt:'INC-035: Systemd-resolved DNS Cache Poisoning Loop',layers:['os','network']},
  {code:'inc_68',grp:'Enterprise Linux Stack',short:'INC-036',txt:'INC-036: Multipathd Daemon Fork Failure Under Device Exhaustion',layers:['os','storage']},
  {code:'inc_25',grp:'Oracle Database Stack',short:'INC-037',txt:'INC-037: Oracle 11g TNS Listener Remote Poisoning Block',layers:['db','network']},
  {code:'inc_26',grp:'Oracle Database Stack',short:'INC-038',txt:'INC-038: Oracle 12c Shared Pool Allocation Memory Leak',layers:['db']},
  {code:'inc_27',grp:'Oracle Database Stack',short:'INC-039',txt:'INC-039: Oracle 19c Data Guard Transport Lag Breakdown',layers:['db','storage']},
  {code:'inc_28',grp:'Oracle Database Stack',short:'INC-040',txt:'INC-040: Oracle 21c Unified Audit Trail Segment Lockup',layers:['db','storage']},
  {code:'inc_29',grp:'Oracle Database Stack',short:'INC-041',txt:'INC-041: Oracle 23c JSON Relational Duality Memory Overrun',layers:['db']},
  {code:'inc_30',grp:'Oracle Database Stack',short:'INC-042',txt:'INC-042: Oracle PL/SQL Native Compilation Workspace Corruption',layers:['db','storage']},
  {code:'inc_31',grp:'Oracle Database Stack',short:'INC-043',txt:'INC-043: Oracle ASM Disk Drop Disconnection',layers:['storage','db']},
  {code:'inc_32',grp:'Oracle Database Stack',short:'INC-044',txt:'INC-044: Oracle TDE Transparent Data Encryption Deadlock',layers:['db','security']},
  {code:'inc_69',grp:'Oracle Database Stack',short:'INC-045',txt:'INC-045 [CVE-2023-22041]: Oracle DB Core RDBMS RCE Vulnerability',layers:['db','security']},
  {code:'inc_70',grp:'Oracle Database Stack',short:'INC-046',txt:'INC-046 [CVE-2024-21099]: Oracle WebLogic Java Serialization Exploit',layers:['app','web','security']},
  {code:'inc_71',grp:'Oracle Database Stack',short:'INC-047',txt:'INC-047: Oracle RAC OCI Network IPC Buffer Starvation',layers:['db','network']},
  {code:'inc_72',grp:'Oracle Database Stack',short:'INC-048',txt:'INC-048: Oracle Undo Tablespace Segment Wrap Forcing Instance Crash',layers:['db','storage']},
  {code:'inc_33',grp:'SAP Sybase ASE Stack',short:'INC-049',txt:'INC-049: Sybase 15.7 Master Device Storage Segment Overflow',layers:['db','storage']},
  {code:'inc_34',grp:'SAP Sybase ASE Stack',short:'INC-050',txt:'INC-050: Sybase 16.0 SP02 Concurrent Query Optimizer Spinlock',layers:['db']},
  {code:'inc_35',grp:'SAP Sybase ASE Stack',short:'INC-051',txt:'INC-051: Sybase 16.0 SP03 Sybmultbuf Backup Server Fault',layers:['db','backup']},
  {code:'inc_36',grp:'SAP Sybase ASE Stack',short:'INC-052',txt:'INC-052: Sybase 16.0 SP04 Remote Procedure Call Context Crash',layers:['db','app']},
  {code:'inc_37',grp:'SAP Sybase ASE Stack',short:'INC-053',txt:'INC-053: Sybase Replication Server Shared Queue Data Drop',layers:['db','network']},
  {code:'inc_38',grp:'SAP Sybase ASE Stack',short:'INC-054',txt:'INC-054: Sybase Adaptive Server Client Connection Buffer Exhaustion',layers:['db','network','app']},
  {code:'inc_39',grp:'SAP Sybase ASE Stack',short:'INC-055',txt:'INC-055: Sybase Local Tempdb Extent Allocation Deadlock',layers:['db','storage']},
  {code:'inc_40',grp:'SAP Sybase ASE Stack',short:'INC-056',txt:'INC-056: Sybase Transaction Log Syslogs Segment Freeze',layers:['db','storage']},
  {code:'inc_73',grp:'SAP Sybase ASE Stack',short:'INC-057',txt:'INC-057 [CVE-2022-41131]: SAP Sybase ASE SQL Injection Bypass',layers:['db','security']},
  {code:'inc_74',grp:'SAP Sybase ASE Stack',short:'INC-058',txt:'INC-058 [CVE-2023-39439]: SAP Sybase Cockpit Directory Traversal',layers:['db','security']},
  {code:'inc_41',grp:'IBM DB2 Stack',short:'INC-061',txt:'INC-061: DB2 10.5 Security Plugin Authentication Memory Fault',layers:['db','security']},
  {code:'inc_42',grp:'IBM DB2 Stack',short:'INC-062',txt:'INC-062: DB2 11.1 HADR Primary Node Heartbeat Dropout',layers:['db','network']},
  {code:'inc_43',grp:'IBM DB2 Stack',short:'INC-063',txt:'INC-063: DB2 11.5 FCM Buffer Starvation',layers:['db','network']},
  {code:'inc_44',grp:'IBM DB2 Stack',short:'INC-064',txt:'INC-064: DB2 11.5.7 Columnar Vector Engine Query Fault',layers:['db']},
  {code:'inc_45',grp:'IBM DB2 Stack',short:'INC-065',txt:'INC-065: DB2 12.1 Tablespace Prefetcher Thread Panic',layers:['db','storage']},
  {code:'inc_46',grp:'IBM DB2 Stack',short:'INC-066',txt:'INC-066: DB2 db2pd Shared Memory Attachment Collision',layers:['db']},
  {code:'inc_47',grp:'IBM DB2 Stack',short:'INC-067',txt:'INC-067: DB2 SQL Compiler Statement Stack Overflow',layers:['db']},
  {code:'inc_48',grp:'IBM DB2 Stack',short:'INC-068',txt:'INC-068: DB2 Direct I/O Block Allocation Mismatch',layers:['db','storage']},
  {code:'inc_77',grp:'IBM DB2 Stack',short:'INC-069',txt:'INC-069 [CVE-2023-38512]: IBM DB2 Information Disclosure Memory Read',layers:['db','security']},
  {code:'inc_78',grp:'IBM DB2 Stack',short:'INC-070',txt:'INC-070 [CVE-2024-22351]: IBM DB2 DoS via Malformed CONNECT Packet',layers:['db','network']},
  {code:'inc_49',grp:'Middleware / Web / CVE',short:'INC-073',txt:'INC-073 [CVE-2021-44228]: Apache Log4j2 JNDI Remote Execution (Log4Shell)',layers:['app','web','security']},
  {code:'inc_50',grp:'Middleware / Web / CVE',short:'INC-074',txt:'INC-074 [CVE-2022-22965]: Spring Framework SpEL Boundary Bypass',layers:['app','web']},
  {code:'inc_51',grp:'Middleware / Web / CVE',short:'INC-075',txt:'INC-075 [CVE-2020-1938]: Apache Tomcat AJP Ghostcat Vulnerability',layers:['web','app']},
  {code:'inc_52',grp:'Middleware / Web / CVE',short:'INC-076',txt:'INC-076 [CVE-2023-32409]: WebKit Enterprise Sandbox Escape',layers:['app','security']},
  {code:'inc_53',grp:'Middleware / Web / CVE',short:'INC-077',txt:'INC-077 [CVE-2022-22963]: Spring Cloud Function ClassLoader Interception',layers:['app']},
  {code:'inc_54',grp:'Middleware / Web / CVE',short:'INC-078',txt:'INC-078 [CVE-2024-3094]: XZ Utils Binary Trojan Backdoor',layers:['os','security']},
  {code:'inc_55',grp:'Middleware / Web / CVE',short:'INC-079',txt:'INC-079 [CVE-2021-34527]: PrintNightmare RPC Spooler Overrun',layers:['os','security']},
  {code:'inc_56',grp:'Middleware / Web / CVE',short:'INC-080',txt:'INC-080 [CVE-2023-4863]: Libwebp Huffman Coding Buffer Crash',layers:['app','web']},
  {code:'inc_57',grp:'Middleware / Web / CVE',short:'INC-081',txt:'INC-081 [CVE-2021-26855]: Exchange Server ProxyLogon SSRF',layers:['web','app','security']},
  {code:'inc_58',grp:'Middleware / Web / CVE',short:'INC-082',txt:'INC-082 [CVE-2024-21626]: runc Container File Descriptor Sandbox Escape',layers:['app','os']},
  {code:'inc_81',grp:'Middleware / Web / CVE',short:'INC-083',txt:'INC-083 [CVE-2024-47575]: Fortinet FortiManager Unauthenticated RCE',layers:['network','security']},
  {code:'inc_82',grp:'Middleware / Web / CVE',short:'INC-084',txt:'INC-084 [CVE-2024-59326]: WhatsUp Gold RCE Deserialization Collapse',layers:['app','security']},
  {code:'inc_83',grp:'Middleware / Web / CVE',short:'INC-085',txt:'INC-085 [CVE-2024-27198]: TeamCity Web UI Authentication Bypass',layers:['app','web','security']},
  {code:'inc_84',grp:'Middleware / Web / CVE',short:'INC-086',txt:'INC-086 [CVE-2025-0221]: OpenSSL ASN.1 Parsing CPU Depletion DoS',layers:['os','security','web']},
  {code:'inc_85',grp:'Middleware / Web / CVE',short:'INC-087',txt:'INC-087 [CVE-2025-10332]: NGINX Ingress Configuration Injection',layers:['web','network']},
  {code:'inc_86',grp:'Middleware / Web / CVE',short:'INC-088',txt:'INC-088 [CVE-2026-0012]: Apache HTTPD Chunked Transfer Corruption',layers:['web','app']},
];

export const FIXES = {
  inc_1:'Format corrupted JFS2 filesystems + rebuild kernel logging structures',
  inc_2:'Rebuild raw ODM device entries via runtime synclvodm and bosboot definitions',
  inc_3:'Correct NIM Master routing config maps and flush stale /etc/hosts entries',
  inc_4:'Tune kernel via chdev to maximize AIO minservers and maxservers bounds',
  inc_5:'Enforce explicit buffer thread sizes inside dsh remote parallel task configs',
  inc_6:'Deploy hardware microcode update for Power9 thread scheduling priority arrays',
  inc_7:'Apply IBM system firmware patch to isolate dynamic slot hotplug LPAR events',
  inc_8:'Isolate WPAR space via distinct network namespace and flag separation configs',
  inc_59:'Apply APAR IJ47321 security patch to eradicate bellmail privilege escalation paths',
  inc_60:'Update AIX libperfstat.a runtime libraries to latest build to plug memory leaks',
  inc_61:'Deactivate LVM quorum constraints using chvg -q n and rebuild volume group metadata',
  inc_62:'Enable iSCSI dynamic path tracking and tune MPIO node discovery timer values',
  inc_9:'Force TLS 1.2/1.3 protocol profiles via Registry; deprecate weak cipher suites',
  inc_10:'Run esentutl offline DB validation and fix bad Active Directory database leaf nodes',
  inc_11:'Tune MSDTC synchronization intervals and extend COM+ transaction timeout windows',
  inc_12:'Deploy WinNAT port pool allocation adjustments using targeted PowerShell configs',
  inc_13:'Import updated root CA certificate arrays to clear Hotpatch signature failures',
  inc_14:'Migrate IIS legacy worker configs to decoupled 64-bit Integrated App Pool modules',
  inc_15:'Configure VSS shadow storage maxsize unlimited; expand provider writer timeouts',
  inc_16:'Modify cluster node voting configs to enforce dynamic split-brain quarantine',
  inc_63:'Deploy cumulative KB5039214 updates to neutralize remote network stack RCE',
  inc_64:'Apply current Windows security rollups to block Kerberos token intercept paths',
  inc_65:'Enforce strict HTTP/2 MaxPendingAccepts and MaxRequests IIS threshold caps',
  inc_66:'Apply LDAP query rate limiting and deny nested recursive LDAP filter sweeps',
  inc_17:'Force immediate upgrade to patched glibc libraries with clean mutex handling',
  inc_18:'Rewrite backend systemd unit scope configs to prevent cgroup memory leak vectors',
  inc_19:'Apply hotfix to isolate NetworkManager D-Bus thread pool message channels',
  inc_20:'Clean stale XFS quota tables and issue xfs_quota structural limit recalculations',
  inc_21:'Shift Podman containers to dedicated systemd cgroup v2 driver runtime configs',
  inc_22:'Refactor application loops to prevent thread blocking inside synchronized Java segments',
  inc_23:'Explicitly reference Jakarta servlet namespaces in target classloader manifest paths',
  inc_24:'Enable secure legacy provider flags inside modern OpenSSL config for compatibility',
  inc_24_1:'Execute urgent system-wide OpenSSH upgrade to 9.8p1+ to mitigate regreSSHion exploit',
  inc_24_2:'Deploy current Linux stable kernel series to address unsafe eBPF processing bugs',
  inc_67:'Disable recursive DNS cache loops inside systemd-resolved global options config',
  inc_68:'Increase global max_fds settings inside multipathd service framework configuration',
  inc_25:'Enable secure Oracle Net listener checking and restrict remote service configs',
  inc_26:'Apply Oracle PSU patch to automate shared pool heap memory recovery loop tuning',
  inc_27:'Tune Data Guard NetTimeout thresholds to preserve async log shipping stability',
  inc_28:'Flush high-frequency audit write targets; shift events to dedicated audit tablespace',
  inc_29:'Adjust internal PGA mapping arrays to tolerate large JSON relational conversions',
  inc_30:'Wipe bad PL/SQL working paths and update ORACLE_HOME compile directory definitions',
  inc_31:'Configure correct ASM disk discovery strings and replace failing physical segments',
  inc_32:'Deploy critical RDBMS software hotfix to clear TDE wallet key rotation deadlocks',
  inc_69:'Install cumulative Oracle CPU quarterly allocation across all nodes',
  inc_70:'Block unsafe Java serialization filter paths inside WebLogic managed server config',
  inc_71:'Optimize RAC interconnect MTU properties and increase IPC network buffer sizes',
  inc_72:'Switch on automatic undo tablespace auto-resize and deploy proactive alert monitors',
  inc_33:'Scale raw database config to expand master device log segment space thresholds',
  inc_34:'Inject targeted hotfix to resolve concurrent optimizer statement parsing spinlocks',
  inc_35:'Deploy Sybmultbuf tracking patch to stabilize multi-threaded Sybase backup hooks',
  inc_36:'Normalize Sybase RPC configuration structures to drop malformed remote exec strings',
  inc_37:'Re-establish active replication rings and flush dead transactional message lines',
  inc_38:'Enlarge inbound client connection thread pool sizes to absorb traffic spike surges',
  inc_39:'Deploy automated partition cleanup tasks to process stale internal storage extents',
  inc_40:'Activate secondary transactional logging targets to balance parallel writing flows',
  inc_73:'Apply SAP security note 3262847 to secure SQL execution paths in ASE Cockpit',
  inc_74:'Disable unauthenticated Cockpit access and close filesystem traversal route vectors',
  inc_41:'Reconfigure DB2 security plugin modules to deploy clean authentication libraries',
  inc_42:'Tune HADR congestion timers and check secondary heartbeat network adapter health',
  inc_43:'Scale up FCM buffer allocation parameters inside db2cfg for fast communications',
  inc_44:'Deploy IBM DB2 engine patch updates to fix columnar vector query processing anomalies',
  inc_45:'Rewrite internal tablespace prefetcher execution threads to safely process containers',
  inc_46:'Correct db2pd diagnostic shared memory layout structures to isolate tool interactions',
  inc_47:'Inject statement length limit caps to block SQL compiler stack overflow loop vectors',
  inc_48:'Switch on raw filesystem allocation configs to resolve DIO block structure mismatches',
  inc_77:'Install targeted DB2 security patch to close engine information exposure read points',
  inc_78:'Apply DB2 system update package to filter out malformed CONNECT payload attacks',
  inc_49:'Upgrade Log4j2 to 2.17.1+; enforce -Dlog4j2.formatMsgNoLookups=true as fallback',
  inc_50:'Apply Spring Framework security updates to close SpEL expression injection windows',
  inc_51:'Disable AJP connector ports or bind Tomcat listeners exclusively to localhost',
  inc_52:'Isolate enterprise application sandboxes and revoke unverified privilege grants',
  inc_53:'Deploy modern Spring Cloud Function dependencies to bypass malicious classloader mutations',
  inc_54:'Purge infected xz-utils binaries system-wide and downgrade to verified stable 5.4.x',
  inc_55:'Deactivate remote printing features and patch Windows Spooler service code paths',
  inc_56:'Apply critical libwebp library modifications to fix Huffman decoding heap flaws',
  inc_57:'Deploy immediate IIS security patches to block unauthorized SSRF hijacking paths',
  inc_58:'Upgrade all host runc engines to v1.1.12+ to eliminate container fd escapes',
  inc_81:'Apply Fortinet firmware hotfixes to block unauthenticated FortiManager remote access',
  inc_82:'Update WhatsUp Gold framework dependencies to secure object deserialization routines',
  inc_83:'Enforce strict token-based validation profiles across all TeamCity UI admin routes',
  inc_84:'Deploy OpenSSL 3.0.13+ to eliminate infinite ASN.1 parsing loop CPU depletion vectors',
  inc_85:'Modify NGINX Ingress setups to prevent unverified custom annotation insertion attacks',
  inc_86:'Apply core Apache HTTPD updates to guarantee correct chunked transfer boundary checking',
};

export function getLayers(codes, allItems) {
  const layers = new Set();
  codes.forEach(code => {
    const item = allItems.find(i => i.code === code);
    if (item) item.layers.forEach(l => layers.add(l));
  });
  return layers;
}
