export const ALL_UUM = [
  // OS Upgrades
  {code:'uum_1',grp:'OS Upgrades',short:'UPG-001',txt:'UPG-001: IBM AIX 7.1 TL5 to AIX 7.3 TL4 In-Place Major Version Upgrade',layers:['os','app'],type:'upgrade'},
  {code:'uum_2',grp:'OS Upgrades',short:'UPG-002',txt:'UPG-002: RHEL 7.9 to RHEL 9.4 In-Place Upgrade via Red Hat Leapp Utility',layers:['os','app'],type:'upgrade'},
  {code:'uum_3',grp:'OS Upgrades',short:'UPG-003',txt:'UPG-003: Windows Server 2016 to Windows Server 2022 LTSC In-Place Upgrade',layers:['os','web','app'],type:'upgrade'},
  {code:'uum_4',grp:'OS Upgrades',short:'UPG-004',txt:'UPG-004: Windows Server 2012 R2 to 2019 LTSC Side-by-Side Migration',layers:['os','web','app'],type:'migration'},
  {code:'uum_5',grp:'OS Upgrades',short:'UPG-005',txt:'UPG-005: Oracle Solaris 10 to Solaris 11.4 Complete Platform Migration',layers:['os','app'],type:'migration'},
  {code:'uum_6',grp:'OS Upgrades',short:'UPG-006',txt:'UPG-006: RHEL 8.x to RHEL 10 Extended Support Path Migration',layers:['os','app'],type:'upgrade'},
  {code:'uum_7',grp:'OS Upgrades',short:'UPG-007',txt:'UPG-007: SUSE SLES 12 SP5 to SLES 15 SP6 Major Version Migration',layers:['os'],type:'upgrade'},
  {code:'uum_8',grp:'OS Upgrades',short:'UPG-008',txt:'UPG-008: AIX 7.2 TL5 Critical OS Technology Level Patch Bundle Update',layers:['os'],type:'update'},
  // Database Migrations
  {code:'uum_9',grp:'Database Migrations',short:'DBM-001',txt:'DBM-001: Oracle DB 11gR2 to Oracle DB 19c Long-Term Release Migration',layers:['db','storage','app'],type:'migration'},
  {code:'uum_10',grp:'Database Migrations',short:'DBM-002',txt:'DBM-002: Oracle DB 12cR2 to Oracle DB 23c Multi-Tenant Architecture Migration',layers:['db','storage','app'],type:'migration'},
  {code:'uum_11',grp:'Database Migrations',short:'DBM-003',txt:'DBM-003: SAP Sybase ASE 15.7 to ASE 16.0 SP04 Platform Migration',layers:['db','app'],type:'upgrade'},
  {code:'uum_12',grp:'Database Migrations',short:'DBM-004',txt:'DBM-004: IBM DB2 LUW 10.5 to DB2 LUW 11.5 Storage Engine Upgrade',layers:['db','storage'],type:'upgrade'},
  {code:'uum_13',grp:'Database Migrations',short:'DBM-005',txt:'DBM-005: IBM DB2 LUW 11.5 to DB2 LUW 12.1 Container Runtime Migration',layers:['db','app'],type:'migration'},
  {code:'uum_14',grp:'Database Migrations',short:'DBM-006',txt:'DBM-006: SQL Server 2012 to SQL Server 2022 Side-by-Side Migration',layers:['db','storage','web'],type:'migration'},
  {code:'uum_15',grp:'Database Migrations',short:'DBM-007',txt:'DBM-007: Oracle DB 19c Critical Patch Update (CPU) Quarterly Bundle Apply',layers:['db'],type:'update'},
  {code:'uum_16',grp:'Database Migrations',short:'DBM-008',txt:'DBM-008: PostgreSQL 13 to PostgreSQL 17 Major Version In-Place Upgrade',layers:['db','storage'],type:'upgrade'},
  // Middleware and App Updates
  {code:'uum_17',grp:'Middleware and App Updates',short:'MWU-001',txt:'MWU-001: WebSphere Application Server 8.5.5 to 9.0.5 FixPack Upgrade',layers:['app','web'],type:'upgrade'},
  {code:'uum_18',grp:'Middleware and App Updates',short:'MWU-002',txt:'MWU-002: Apache Tomcat 8.5 EOL to Tomcat 10.1 Jakarta EE Migration',layers:['app','web'],type:'migration'},
  {code:'uum_19',grp:'Middleware and App Updates',short:'MWU-003',txt:'MWU-003: JBoss EAP 6.4 to JBoss EAP 8.0 Jakarta EE Platform Migration',layers:['app','web'],type:'migration'},
  {code:'uum_20',grp:'Middleware and App Updates',short:'MWU-004',txt:'MWU-004: Oracle WebLogic Server 12.1.3 to WebLogic 14.1.2 Upgrade',layers:['app','web'],type:'upgrade'},
  {code:'uum_21',grp:'Middleware and App Updates',short:'MWU-005',txt:'MWU-005: Java 8 to Java 21 LTS Runtime Migration across All Application Tiers',layers:['app','os'],type:'migration'},
  {code:'uum_22',grp:'Middleware and App Updates',short:'MWU-006',txt:'MWU-006: .NET Framework 4.8 to .NET 8.0 LTS Side-by-Side Migration',layers:['app','web'],type:'migration'},
  {code:'uum_23',grp:'Middleware and App Updates',short:'MWU-007',txt:'MWU-007: SAP NetWeaver 7.40 to NetWeaver 7.50 Support Package Stack',layers:['app'],type:'update'},
  {code:'uum_24',grp:'Middleware and App Updates',short:'MWU-008',txt:'MWU-008: IBM Open Liberty 22.x to Liberty 24.x Quarterly Feature Update',layers:['app'],type:'update'},
  // Web Server Upgrades
  {code:'uum_25',grp:'Web Server Upgrades',short:'WSU-001',txt:'WSU-001: Apache HTTPD 2.2 EOL to HTTPD 2.4 MPM-Worker Production Upgrade',layers:['web'],type:'upgrade'},
  {code:'uum_26',grp:'Web Server Upgrades',short:'WSU-002',txt:'WSU-002: IIS 8.5 to IIS 10 Application Pool Modernization Upgrade',layers:['web','os'],type:'upgrade'},
  {code:'uum_27',grp:'Web Server Upgrades',short:'WSU-003',txt:'WSU-003: NGINX 1.18 to NGINX 1.26 LTS Production Stream Upgrade',layers:['web'],type:'update'},
  {code:'uum_28',grp:'Web Server Upgrades',short:'WSU-004',txt:'WSU-004: IBM HTTP Server (IHS) 8.5 to IHS 9.0.5 FixPack Upgrade',layers:['web'],type:'upgrade'},
  {code:'uum_29',grp:'Web Server Upgrades',short:'WSU-005',txt:'WSU-005: SSL/TLS 1.0/1.1 Full Deprecation and TLS 1.3 Enforcement Migration',layers:['web','security','os'],type:'update'},
  {code:'uum_30',grp:'Web Server Upgrades',short:'WSU-006',txt:'WSU-006: Apache HTTPD ModSecurity WAF Rule Set Annual Refresh',layers:['web','security'],type:'update'},
  // Security and Compliance
  {code:'uum_31',grp:'Security and Compliance Updates',short:'SEC-001',txt:'SEC-001: IBM Power Firmware and Microcode Annual Critical Security Update',layers:['hardware','os'],type:'update'},
  {code:'uum_32',grp:'Security and Compliance Updates',short:'SEC-002',txt:'SEC-002: OS Kernel CVE Consolidated Patch Bundle Annual Security Update',layers:['os','security'],type:'update'},
  {code:'uum_33',grp:'Security and Compliance Updates',short:'SEC-003',txt:'SEC-003: OpenSSL 1.1.x EOL to OpenSSL 3.x Migration across All Platforms',layers:['os','web','security'],type:'migration'},
  {code:'uum_34',grp:'Security and Compliance Updates',short:'SEC-004',txt:'SEC-004: Enterprise PKI Certificate Authority Rotation and CRL Refresh',layers:['security','web'],type:'update'},
  {code:'uum_35',grp:'Security and Compliance Updates',short:'SEC-005',txt:'SEC-005: SIEM and Security Tooling Annual Platform and Ruleset Upgrade',layers:['security'],type:'upgrade'},
  {code:'uum_36',grp:'Security and Compliance Updates',short:'SEC-006',txt:'SEC-006: SSH Key Infrastructure Rotation and FIPS 140-3 Compliance Migration',layers:['security','os','network'],type:'update'},
  // Platform and Storage Migrations
  {code:'uum_37',grp:'Platform and Storage Migrations',short:'PLT-001',txt:'PLT-001: IBM Power7/Power8 LPAR to Power10 Infrastructure Blade Migration',layers:['hardware','os','storage'],type:'migration'},
  {code:'uum_38',grp:'Platform and Storage Migrations',short:'PLT-002',txt:'PLT-002: On-Premises x86 Rack to AWS Graviton4 ARM64 Cloud Migration',layers:['hardware','os','app','storage'],type:'migration'},
  {code:'uum_39',grp:'Platform and Storage Migrations',short:'PLT-003',txt:'PLT-003: Oracle ASM Traditional Disk Group to ASM Flex Diskgroup Migration',layers:['storage','db'],type:'migration'},
  {code:'uum_40',grp:'Platform and Storage Migrations',short:'PLT-004',txt:'PLT-004: Legacy SAN FC Fabric to NVMe over Fabric (NVMe-oF) Migration',layers:['storage'],type:'migration'},
  {code:'uum_41',grp:'Platform and Storage Migrations',short:'PLT-005',txt:'PLT-005: Physical Tape Backup to Cloud-Native Veeam DR Migration',layers:['backup'],type:'migration'},
  {code:'uum_42',grp:'Platform and Storage Migrations',short:'PLT-006',txt:'PLT-006: IBM TSM / Spectrum Protect 7.x to Spectrum Protect 8.1 Upgrade',layers:['backup','storage'],type:'upgrade'},
  // Proactive Hardening
  {code:'uum_43',grp:'Proactive Hardening and Resilience',short:'PRO-001',txt:'PRO-001: Proactive Kernel Live Patching via kpatch / ksplice without System Reboot',layers:['os'],type:'update'},
  {code:'uum_44',grp:'Proactive Hardening and Resilience',short:'PRO-002',txt:'PRO-002: Proactive Memory Pressure Monitoring and Threshold Alerting Baseline',layers:['os','hardware'],type:'update'},
  {code:'uum_45',grp:'Proactive Hardening and Resilience',short:'PRO-003',txt:'PRO-003: Proactive Disk I/O Latency Baselining and Performance Trend Analysis',layers:['storage','os'],type:'update'},
  {code:'uum_46',grp:'Proactive Hardening and Resilience',short:'PRO-004',txt:'PRO-004: Proactive Network Bandwidth Saturation and Bottleneck Simulation Testing',layers:['network','os'],type:'update'},
  {code:'uum_47',grp:'Proactive Hardening and Resilience',short:'PRO-005',txt:'PRO-005: Proactive SSL/TLS Certificate Expiry Automation and Renewal Pipeline Build',layers:['web','security'],type:'update'},
  {code:'uum_48',grp:'Proactive Hardening and Resilience',short:'PRO-006',txt:'PRO-006: Proactive Disaster Recovery Failover Simulation and RTO/RPO Validation Exercise',layers:['backup','storage'],type:'update'},
  {code:'uum_49',grp:'Proactive Hardening and Resilience',short:'PRO-007',txt:'PRO-007: Proactive Database Vacuum, RUNSTATS, and Statistics Refresh Scheduling',layers:['db'],type:'update'},
  {code:'uum_50',grp:'Proactive Hardening and Resilience',short:'PRO-008',txt:'PRO-008: Proactive Log Rotation, Archive Purge, and Retention Policy Automation',layers:['os','storage'],type:'update'},
  // Cross-Platform Migrations (subset)
  {code:'uum_63',grp:'Cross-Platform and Cost Reduction Migrations',short:'CPM-001',txt:'CPM-001: IBM AIX 7.x LPAR to Red Hat Enterprise Linux on IBM Power (PowerVM) Migration',layers:['os','app','storage'],type:'migration'},
  {code:'uum_64',grp:'Cross-Platform and Cost Reduction Migrations',short:'CPM-002',txt:'CPM-002: AIX Monolithic Workloads to RHEL for SAP on IBM Power10 Cost Reduction Migration',layers:['os','app','db'],type:'migration'},
  {code:'uum_65',grp:'Cross-Platform and Cost Reduction Migrations',short:'CPM-003',txt:'CPM-003: IBM Power7 and Power8 Legacy LPARs to Power10 Linux LPARs Infrastructure Migration',layers:['hardware','os','storage'],type:'migration'},
  {code:'uum_66',grp:'Cross-Platform and Cost Reduction Migrations',short:'CPM-004',txt:'CPM-004: Windows Server x86 Workloads to RHEL 9 Side-by-Side OS Consolidation Migration',layers:['os','web','app'],type:'migration'},
  {code:'uum_67',grp:'Cross-Platform and Cost Reduction Migrations',short:'CPM-005',txt:'CPM-005: Oracle Database 11g and 12c to PostgreSQL 16 Open Source Cost Reduction Migration',layers:['db','storage','app'],type:'migration'},
  {code:'uum_68',grp:'Cross-Platform and Cost Reduction Migrations',short:'CPM-006',txt:'CPM-006: SAP Sybase ASE to SAP HANA 2.0 SPS07 In-Memory High Performance Platform Migration',layers:['db','storage','app'],type:'migration'},
  {code:'uum_85',grp:'Cross-Platform and Cost Reduction Migrations',short:'CPM-023',txt:'CPM-023: Legacy Monolithic Application to Docker Containerization and Kubernetes Orchestration Migration',layers:['app','os','network'],type:'migration'},
  // Missing Path Gap-Fill
  {code:'uum_93',grp:'Missing Path Gap-Fill UUM Items',short:'GAP-001',txt:'GAP-001: RHEL 6.x EOL (Nov 2020) to RHEL 8.10 Maintenance Branch Side-by-Side Migration -- Critical Path',layers:['os','app','web'],type:'migration'},
  {code:'uum_94',grp:'Missing Path Gap-Fill UUM Items',short:'GAP-002',txt:'GAP-002: RHEL 7.x EOS (Jun 2024) to RHEL 9.4 Production via Red Hat Leapp Two-Stage Upgrade',layers:['os','app'],type:'upgrade'},
  {code:'uum_104',grp:'Missing Path Gap-Fill UUM Items',short:'GAP-012',txt:'GAP-012: Oracle Database 19c to Oracle DB 23c Multi-Tenant Architecture Upgrade (Next LTS Path)',layers:['db','storage','app'],type:'upgrade'},
  {code:'uum_107',grp:'Missing Path Gap-Fill UUM Items',short:'GAP-015',txt:'GAP-015: PostgreSQL 9.6 / 10 EOL to PostgreSQL 16 LTS Major Version Migration via pg_upgrade',layers:['db','storage'],type:'migration'},
  {code:'uum_115',grp:'Missing Path Gap-Fill UUM Items',short:'GAP-023',txt:'GAP-023: Ubuntu Server 22.04 LTS to Ubuntu 24.04 LTS Noble Numbat In-Place do-release-upgrade',layers:['os','app'],type:'upgrade'},
  {code:'uum_116',grp:'Missing Path Gap-Fill UUM Items',short:'GAP-024',txt:'GAP-024: CentOS 7 / CentOS 8 EOL Migration to AlmaLinux 8.x or Rocky Linux 8.x RHEL-Compatible Path',layers:['os','app','web'],type:'migration'},
];
